apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: Z3JhcGhzUmNvb2w=
  GF_SECURITY_ADMIN_USER: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: grafana-creds
  selfLink: /api/v1/namespaces/default/secrets/grafana-creds
type: Opaque
