apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana
  selfLink: /api/v1/namespaces/default/services/grafana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32321
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
