apiVersion: v1
data:
  INFLUXDB_DATABASE: dHdpdHRlcmdyYXBo
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: cm9vdA==
  INFLUXDB_USERNAME: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: influxdb-creds
  selfLink: /api/v1/namespaces/default/secrets/influxdb-creds
type: Opaque
